name: Mautic tests and validations

on:
  push:
    branches:
      - 'fix-*'
  pull_request:
  merge_group:
  schedule:
    # Run every day at 10:45 AM UTC to discover potential issues with dependencies like PHP updates etc.
    - cron: '45 10 * * *'

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  phpunit:
    # We don't want the scheduled jobs to run on forks of Mautic
    if: (github.event_name == 'schedule' && (github.repository == 'mautic/mautic' || github.repository == 'mautic/api-library') ) || (github.event_name != 'schedule')
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['8.4']
        db-types: ['mysql:8.4']

    name: PHPUnit ${{ matrix.php-versions }} ${{ matrix.db-types }}

    services:
      database:
        image: ${{ matrix.db-types }}
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: mautictest
        ports:
          - 3306
        options: >-
          --shm-size=2gb
          --tmpfs=/var/lib/mysql
          --health-cmd "${{ startsWith(matrix.db-types, 'mysql:') && 'mysqladmin ping' || 'healthcheck.sh --connect --innodb_initialized' }}"
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3
      saml:
        image: kenchan0130/simplesamlphp
        env:
          SIMPLESAMLPHP_SP_ENTITY_ID: https://localhost
          SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: https://localhost/s/saml/login_check
          SIMPLESAMLPHP_IDP_BASE_URL: http://localhost:8086/simplesaml/
        ports:
          - 8086:8080

    steps:
    - uses: actions/checkout@v4
      # Codecov needs access to previous commits, so we add fetch-depth: 0
      with:
        fetch-depth: 0

    - name: PHPUnit cache
      if: ${{matrix.php-versions == '8.2' && matrix.db-types == 'mariadb:10.11'}}
      uses: actions/cache@v4
      with:
        path: ./var/cache/phpunit
        key: ${{ runner.os }}-phpunit-${{ hashFiles('**/composer.lock') }}-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-phpunit-${{ hashFiles('**/composer.lock') }}
          ${{ runner.os }}-phpunit-

    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql, pdo_mysql
        coverage: pcov
        ini-values: pcov.enabled=0, pcov.directory=., pcov.exclude="~tests|themes|vendor~", zend.assertions=1

    - name: add MySQL config file
      run: |
        mysqldump --version
        mysqldump --print-defaults
        cp .github/ci-files/.my.cnf ~/.my.cnf
        mysqldump --print-defaults
        DB_LOG_NAME="${{ matrix.db-types }}"
        echo "DB_LOG_NAME=${DB_LOG_NAME/:/_}" >> $GITHUB_ENV

    - name: Set SYMFONY_ENV to test
      run: |
        echo "SYMFONY_ENV=test" >> $GITHUB_ENV
        echo "MAUTIC_ENV=test" >> $GITHUB_ENV

    - name: Install dependencies
      # composer install cache - https://github.com/ramsey/composer-install
      uses: "ramsey/composer-install@v3"

    - name: Run tests - database = ${{ matrix.db-types }}
      run: |
        rm -rf var/cache
        export DB_PORT="${{ job.services.database.ports[3306] }}"
        export SAML_PORT="${{ job.services.saml.ports[8080] }}"

        php -d zend.assertions=1 bin/phpunit -d memory_limit=2G --bootstrap vendor/autoload.php --configuration app/phpunit.xml.dist app/bundles/PageBundle/Tests/Controller

